export const homeEnding: string;
export const end_img: string;
export const endImg: string;
export const Info: string;
export const info: string;
export const information: string;
export const Con: string;
export const con: string;
export const contact: string;
